
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}

###
POST http://localhost:5000/admin/get/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk3OTU0NDUsImV4cCI6MTY2OTc5NjM0NX0.bSjqrUzFF4Uv_R9tvyooyB_4jT0JD87wOftyBpLSgcc
Content-Type: application/json

{
    "id" : "",
    "username" : "",
    "fullname" : "",
    "intake" : "",
    "email" : "",
    "ects" : "",
    "signature" : "",
    "page" : "1"
}
###
GET http://localhost:5000/admin/get/student/13961
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk4NzU4ODEsImV4cCI6MTY2OTg3Njc4MX0.uk0B87DRRgxv6yP4PEJ6sR2Pii7Jd9EveeoBMhJyA5I

###
GET http://localhost:5000/admin/get/student/13961/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk3OTU4MzksImV4cCI6MTY2OTc5NjczOX0.fh3u2QXSZ_Y1F0DtykTDIq9jVbfNM1-w6bfiKq-Dvlo

###
GET http://localhost:5000/admin/get/student/13961/assessmentBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk3OTU4MzksImV4cCI6MTY2OTc5NjczOX0.fh3u2QXSZ_Y1F0DtykTDIq9jVbfNM1-w6bfiKq-Dvlo

###
GET http://localhost:5000/admin/get/student/13961/registrationOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk3OTU4MzksImV4cCI6MTY2OTc5NjczOX0.fh3u2QXSZ_Y1F0DtykTDIq9jVbfNM1-w6bfiKq-Dvlo

###
GET http://localhost:5000/admin/get/student/13961/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk3OTU4MzksImV4cCI6MTY2OTc5NjczOX0.fh3u2QXSZ_Y1F0DtykTDIq9jVbfNM1-w6bfiKq-Dvlo

###

POST http://localhost:3001/addSocket
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxOTIwNjQsImV4cCI6MTY2ODE5MjA5NH0.1QdCjEGNYw07-_6h5O1UoUvd_8D2ZE1tNr7MueR09WQ

### 
POST http://localhost:5000/admin/add/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0MjU2NTAsImV4cCI6MTY2ODQyNjU1MH0.bJKAzzwcIDL2BS2QQwOdncNQaY8ZWSHZJRYCFfpCJWs
Content-Type: application/json

{
    "id" : 12345,
    "username" : "12345",
    "fullname" : "haotran",
    "email" : "haotran@gmail.com",
    "intake" : "123",
    "ects" : "168",
    "signature" : "signature"
}

###
PUT http://localhost:5000/admin/update/student/12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0MjU3MTIsImV4cCI6MTY2ODQyNjYxMn0.PFIxoIdOv9d7IgszUa8hcAuj6zbjXcWrBvQbHYIgz8I
Content-Type: application/json

{
    "username" : "linh",
    "fullname" : "linhkhanhtran_updated",
    "intake" : "2018",
    "email" : "linh1@gmail.com",
    "ects" : 168,
    "signature" : "signature"
}
###
DELETE http://localhost:5000/admin/delete/student/12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0MjU3MTIsImV4cCI6MTY2ODQyNjYxMn0.PFIxoIdOv9d7IgszUa8hcAuj6zbjXcWrBvQbHYIgz8I