###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "tiffany",
    "password" : "23483"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "romein",
    "password" : "20489"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "mikadang",
    "password" : "22323"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "longle",
    "password" : "21933"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "alexnguyen",
    "password" : "21029"
}
###
GET http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzA4NTg0NDIsImV4cCI6MTY3MDg1OTM0Mn0.2Y-85x-yhoZezZHoyWBc3TmTObjnjyVwE-hTWpxDCB8

###
POST http://localhost:5000/lecturer1/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NjEwMDk4MiwiZXhwIjoxNjc2MTAxODgyfQ.uF6clasaontwMzrS0wD-he8paU03Xc2byHXHHqby8tE
Content-Type: application/json

{
    "thesisTopic" : "Data test",
    "thesisField" : "Data test field",
    "slotMaximum" : 2
}

###
POST http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NjI5MDc3MywiZXhwIjoxNjc2MjkxNjczfQ.wq5G2NrRpYMxqiIBkpc2sQnww20qhrQQ7URryIlGEUU
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer1Title" : "",
    "lecturer2Title" : "",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "",
    "wasDefended" : false,
    "page" : 1
}

###
POST http://localhost:5000/lecturer2/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3NTkxODAwNywiZXhwIjoxNjc1OTE4OTA3fQ.lEOpFvEwH6iSyh_sAXNpzwYLFsQhE1hB_Z8LnPEV-bY
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer1Title" : "e",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "",
    "confirmSup2" : "",
    "wasDefended" : false,
    "page" : 1
}


###
GET http://localhost:5000/lecturer1/get/thesis/123342
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NjA5OTcyNiwiZXhwIjoxNjc2MTAwNjI2fQ.LvCS50GrUYy7H7jkU40PCXhZli8svDh-EvN61ns55C0

###
GET http://localhost:5000/lecturer2/get/thesis/210292
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MzUxMTk2OCwiZXhwIjoxNjczNTEyODY4fQ.ZbhbW_E_3N18s77gl56WqHYklosIVKcMcYOtJVUOEl8

###
POST http://localhost:5000/lecturer1/confirm/confirmStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMzMjIwMiwiZXhwIjoxNjcyMzMzMTAyfQ.JYECVPegzOjvhrxteTw8RaMEfgb5W8yMFmcuFSuIqfA
Content-Type: application/json

{
    "studentId" : 12211,
    "confirmStudent" : false
}

###
POST http://localhost:5000/lecturer2/confirm/confirmThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjMzMDk4NCwiZXhwIjoxNjcyMzMxODg0fQ.VUajfetgS8nQSoW4K-FOj52GR7_cFcVBzoVCxuNjCa0
Content-Type: application/json

{
    "thesisId" : 123554,
    "confirmThesis" : false
}
###
POST http://localhost:5000/lecturer1/confirm/confirmThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMzMDc3OSwiZXhwIjoxNjcyMzMxNjc5fQ.TvXH8CcrbDmlzf4hfn0ZqFNvXVnoqhEGc25cNA2e6qY
Content-Type: application/json

{
    "thesisId" : 123454,
    "confirmThesis" : true
}

###
POST http://localhost:5000/lecturer1/signIn/registrationBachelorThesisAsSup1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMxMjU1MCwiZXhwIjoxNjcyMzEzNDUwfQ.li54BHpN1eKakY6jvu5K9Ysi7wj4UwHIt3Lif95eZ7M
Content-Type: application/json

{
    "studentId" : 12486,
    "confirmSignature" : true
}
###
POST http://localhost:5000/lecturer1/signIn/registrationBachelorThesisAsSup2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMxMjUxMiwiZXhwIjoxNjcyMzEzNDEyfQ.JJoKeSupwsqfFUFCOkthyg4FgDRfikrJQO-1PSF9qOE
Content-Type: application/json

{
    "studentId" : 19363,
    "confirmSignature" : true
}


###
POST http://localhost:5000/lecturer2/signIn/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjMxMjY4OCwiZXhwIjoxNjcyMzEzNTg4fQ.Nsl3UGqQlI8UAhTIkMMOwsTo9wn3hA3NEGBnYatg1Q4
Content-Type: application/json

{
    "studentId" : 12323,
    "confirmSignature" : true
}


###
PUT http://localhost:5000/lecturer1/update/assessmentBachelor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTgzNDA5OSwiZXhwIjoxNjc1ODM0OTk5fQ.8gsINhaEx2FRcsNVf1LtOkCb-pdah9KZsS7FVLR-ncI
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen1",
    "foreName" : "long1",
    "thesisTitle" : "title 12486 update lecturer1",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu of lecturer1 ",
    "supervisor1_grade" : 1.5,
    "supervisor2_title" : "Master Huynh Nguyen of lec1",
    "supervisor2_grade" : 1.2,
    "assessmentThesis" : "This is assessment Thesis lec1",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer1/update/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTgzNDA5OSwiZXhwIjoxNjc1ODM0OTk5fQ.8gsINhaEx2FRcsNVf1LtOkCb-pdah9KZsS7FVLR-ncI
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen1",
    "foreName" : "long1",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu of lecturer1",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen of lec1", 
    "supervisor2_grade" : 1.3,
    "record" : "This is record",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer2/update/assessmentBachelor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3NTgzNDAzOCwiZXhwIjoxNjc1ODM0OTM4fQ.kmV5MIFVZ-QIWAqu7bZdAAZtBf50jqpwF1f7yeRRzEo
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen12",
    "foreName" : "long",
    "thesisTitle" : "thesis title 2",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu 2",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen 2",
    "supervisor2_grade" : 1.1,
    "assessmentThesis" : "This is assessment Thesis test for lecturer2",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer2/update/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3NTgzNDAzOCwiZXhwIjoxNjc1ODM0OTM4fQ.kmV5MIFVZ-QIWAqu7bZdAAZtBf50jqpwF1f7yeRRzEo
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu 2",
    "supervisor1_grade" : 1.2,
    "supervisor2_title" : "Master Huynh Nguyen 2", 
    "supervisor2_grade" : 1.2,
    "record" : "This is record 2",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
GET http://localhost:5000/lecturer1/get/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTgzNTY0NiwiZXhwIjoxNjc1ODM2NTQ2fQ.c8udrhXzroy2XH15DYBmimgM29LyTiU5PHV84yfeklE

###
GET http://localhost:5000/lecturer2/get/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3NTgzNTg2MCwiZXhwIjoxNjc1ODM2NzYwfQ.86SSu4cZDZ93Mbyl-uhMpGz2jFCZfWY6Il6ZoToK_Gs

###
PUT http://localhost:5000/lecturer1/update/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTg2NTY0NSwiZXhwIjoxNjc1ODY2NTQ1fQ.eudyBcZujAvI6v3p9I0rS7gCKaP9VdJq2JGfMv2tYgs
Content-Type: application/json

{
    "title" : "Dr.Test 1",
    "email" : "sadl@gmail.com",
    "maximum_of_theses" : 1,
    "bio" : "This is test for 1",
    "signature" : "singature"
}