###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "alexnguyen",
    "password" : "21029"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "romein",
    "password" : "20489"
}

###
GET http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzA4NTg0NDIsImV4cCI6MTY3MDg1OTM0Mn0.2Y-85x-yhoZezZHoyWBc3TmTObjnjyVwE-hTWpxDCB8

###
POST http://localhost:5000/lecturer1/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MDg2MTgxMSwiZXhwIjoxNjcwODYyNzExfQ.IVtEqwDSqRCeTec7wCD6LNTbmLjjq5l-bn4qHaekdJg
Content-Type: application/json

{
    "thesisId" : 201202,
    "thesisTopic" : "Data test",
    "thesisField" : "Data test field",
    "slotMaximum" : 2
}

###
POST http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjIzMDgwNiwiZXhwIjoxNjcyMjMxNzA2fQ.ydfodT7EoSLQgOPCXVYUs3tSGtEHg3L3ULoScf3Asho
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer2Id" : "",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "",
    "page" : 1
}

###
POST http://localhost:5000/lecturer2/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjIzMDUxMSwiZXhwIjoxNjcyMjMxNDExfQ.nAiuqw_05GJRuKlfNXKQd56KCr09oEdR5kvzAuDAX3Q
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer1Id" : "",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "",
    "confirmSup2" : "",
    "page" : 1
}


###
GET http://localhost:5000/lecturer1/get/thesis/210291
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjIyNzQzMiwiZXhwIjoxNjcyMjI4MzMyfQ.Q-HaIfsyRs1HovP6O6w-yMOfMdbJesTYWoxGT6s2Umc

###
GET http://localhost:5000/lecturer2/get/thesis/210291
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjIyNzYzNCwiZXhwIjoxNjcyMjI4NTM0fQ.lGEgvAFcADziVPH2LgoJ_UYOFHQLN8GdUdabzQJE_z4

###
POST http://localhost:5000/lecturer1/confirm/confirmStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MTAzMzU3MCwiZXhwIjoxNjcxMDM0NDcwfQ.CGOGl5wnkoep15nByotQr3TNnB2nMf4Cy2ysbGILDXI
Content-Type: application/json

{
    "studentId" : 12211,
    "confirmStudent" : true
}

###
POST http://localhost:5000/lecturer2/confirm/confirmThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MTAzNzMyOSwiZXhwIjoxNjcxMDM4MjI5fQ.piTqf4TBHWtTPsQhf9oxbGqWJxbd7m4gAgKxOGHU8l0
Content-Type: application/json

{
    "thesisId" : 123554,
    "confirmThesis" : true
}

###
POST http://localhost:5000/lecturer1/signIn/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MTEyMjY5NywiZXhwIjoxNjcxMTIzNTk3fQ.jsBHsSxQghE7HiIucoCnbmtptjzfbVb_4kaT3Fv7DBI
Content-Type: application/json

{
    "studentId" : 12486,
    "confirmSignature" : false
}

###
POST http://localhost:5000/lecturer2/signIn/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MTEyOTIzOCwiZXhwIjoxNjcxMTMwMTM4fQ.CeGGDBy3izZPyIVLktToHULjvHBpjM3mW--sAv0BngM
Content-Type: application/json

{
    "studentId" : 19363,
    "confirmSignature" : true
}