###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "tiffany",
    "password" : "23483"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "romein",
    "password" : "20489"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "romein",
    "password" : "20489"
}

###
GET http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzA4NTg0NDIsImV4cCI6MTY3MDg1OTM0Mn0.2Y-85x-yhoZezZHoyWBc3TmTObjnjyVwE-hTWpxDCB8

###
POST http://localhost:5000/lecturer1/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTUyMjA4OSwiZXhwIjoxNjc1NTIyOTg5fQ.VZtj8nbNNCBMkENRYFPnKWOgiEXOvh_YvemCvH_jEbM
Content-Type: application/json

{
    "thesisTopic" : "Data test",
    "thesisField" : "Data test field",
    "slotMaximum" : 2
}

###
POST http://localhost:5000/lecturer1/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMzMTU4OSwiZXhwIjoxNjcyMzMyNDg5fQ.UXMAIlG2twFJZeE-G9VZh-q2HetuyVhkx-0y0qkyicA
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer2Id" : "",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "2",
    "page" : 1
}

###
POST http://localhost:5000/lecturer2/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjIzMDUxMSwiZXhwIjoxNjcyMjMxNDExfQ.nAiuqw_05GJRuKlfNXKQd56KCr09oEdR5kvzAuDAX3Q
Content-Type: application/json

{
    "thesisTopic" : "",
    "thesisField" : "",
    "lecturer1Id" : "",
    "step" : "",
    "slot" : "",
    "slotMaximum" : "",
    "confirmSup2" : "",
    "page" : 1
}


###
GET http://localhost:5000/lecturer1/get/thesis/123342
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTU3OTg3NCwiZXhwIjoxNjc1NTgwNzc0fQ.coE6ok5HXJQm3Jsf92zw-VBBdYlweIFRba6kqB_Abos

###
GET http://localhost:5000/lecturer2/get/thesis/210292
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MzUxMTk2OCwiZXhwIjoxNjczNTEyODY4fQ.ZbhbW_E_3N18s77gl56WqHYklosIVKcMcYOtJVUOEl8

###
POST http://localhost:5000/lecturer1/confirm/confirmStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMzMjIwMiwiZXhwIjoxNjcyMzMzMTAyfQ.JYECVPegzOjvhrxteTw8RaMEfgb5W8yMFmcuFSuIqfA
Content-Type: application/json

{
    "studentId" : 12211,
    "confirmStudent" : false
}

###
POST http://localhost:5000/lecturer2/confirm/confirmThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjMzMDk4NCwiZXhwIjoxNjcyMzMxODg0fQ.VUajfetgS8nQSoW4K-FOj52GR7_cFcVBzoVCxuNjCa0
Content-Type: application/json

{
    "thesisId" : 123554,
    "confirmThesis" : false
}
###
POST http://localhost:5000/lecturer1/confirm/confirmThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMzMDc3OSwiZXhwIjoxNjcyMzMxNjc5fQ.TvXH8CcrbDmlzf4hfn0ZqFNvXVnoqhEGc25cNA2e6qY
Content-Type: application/json

{
    "thesisId" : 123454,
    "confirmThesis" : true
}

###
POST http://localhost:5000/lecturer1/signIn/registrationBachelorThesisAsSup1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMxMjU1MCwiZXhwIjoxNjcyMzEzNDUwfQ.li54BHpN1eKakY6jvu5K9Ysi7wj4UwHIt3Lif95eZ7M
Content-Type: application/json

{
    "studentId" : 12486,
    "confirmSignature" : true
}
###
POST http://localhost:5000/lecturer1/signIn/registrationBachelorThesisAsSup2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEwMjksInVzZXJuYW1lIjoiYWxleG5ndXllbiIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3MjMxMjUxMiwiZXhwIjoxNjcyMzEzNDEyfQ.JJoKeSupwsqfFUFCOkthyg4FgDRfikrJQO-1PSF9qOE
Content-Type: application/json

{
    "studentId" : 19363,
    "confirmSignature" : true
}


###
POST http://localhost:5000/lecturer2/signIn/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3MjMxMjY4OCwiZXhwIjoxNjcyMzEzNTg4fQ.Nsl3UGqQlI8UAhTIkMMOwsTo9wn3hA3NEGBnYatg1Q4
Content-Type: application/json

{
    "studentId" : 12323,
    "confirmSignature" : true
}


###
PUT http://localhost:5000/lecturer1/update/assessmentBachelor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTU5MzI5NiwiZXhwIjoxNjc1NTk0MTk2fQ.xtruw7uyrMPMJ55GKAeS17zzxkVu-DvdVPImibUhPWQ
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_grade" : 1.5,
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_grade" : 1.2,
    "assessmentThesis" : "This is assessment Thesis",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer1/update/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTU5MjMxNiwiZXhwIjoxNjc1NTkzMjE2fQ.DJ7GXsSx_hom3CeO9K9hpZ1HlUrGKdWuQ3s8VmguzPw
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen", 
    "supervisor2_grade" : 1.3,
    "record" : "This is record",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer2/update/assessmentBachelor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0ODksInVzZXJuYW1lIjoicm9tZWluIiwicm9sZSI6IltcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY3NTU5MzIxOSwiZXhwIjoxNjc1NTk0MTE5fQ.pxx43wrbbu5sDEMKVIVvMRbamFR1ytlWNHTak3o8c4w
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen12",
    "foreName" : "long",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_grade" : 1.5,
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_grade" : 1.2,
    "assessmentThesis" : "This is assessment Thesis test for lecturer2",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
PUT http://localhost:5000/lecturer2/update/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0ODMsInVzZXJuYW1lIjoidGlmZmFueSIsInJvbGUiOiJbXCJsZWN0dXJlcjEuMVwiXSIsImlhdCI6MTY3NTU5MjMxNiwiZXhwIjoxNjc1NTkzMjE2fQ.DJ7GXsSx_hom3CeO9K9hpZ1HlUrGKdWuQ3s8VmguzPw
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen", 
    "supervisor2_grade" : 1.3,
    "record" : "This is record",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}
