POST http://localhost:4000/signup
Content-Type: application/json

{
    "id" : "21457",
    "username" : "haotran12",
    "password" : "21457",
    "role" : ["lecturer1.1"]
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}
###
GET http://localhost:5000/getNotifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk2NTI3OTgsImV4cCI6MTY2OTY1MzY5OH0.FSBZdiyeuybzuWQbAgzv88tVSxpyCmfZ7gHvVqH3Inw

###
GET http://localhost:4000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NjgwMDI5MCwiZXhwIjoxNjY2ODAwMzIwfQ.gZgsEh7TR89gz8yuA0iwrkx9Pw7xzbu4pOBNx6tJuyk
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTE5MCwiZXhwIjoxNjY2NDM4NzkwfQ.hKxDcBkq15hNjD9W8TPp1uErxPpG1TTGGIW0-DQjYVU"
}

###
GET http://localhost:5000/admin/get/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxNjYzMjcsImV4cCI6MTY2ODE2NjM1N30.gPxyJo4AmL92o-Slzcqfpa4k-lXA092S99FzaNeaAH0

###
GET http://localhost:5000/admin/get1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqYW1lczIiLCJyb2xlIjoibGVjdHVyZXIxIiwiaWF0IjoxNjY2NDE2NzkxLCJleHAiOjE2NjY0MTY4MjF9.TxOqq6TGCqAkuNVt3ARtDaiARcHPKfib1sumYLa8zq4

###
GET http://localhost:5000/admin/get2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQxNzYwMCwiZXhwIjoxNjY2NDE3NjMwfQ.bpYOUSeeK1f-D9shUCENja1Tq7VGyyGj4Qajt_lRRXU


###
GET http://localhost:5000/lecturer1/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqYW1lczEwMSIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIxXCJdIiwiaWF0IjoxNjY2NTk2MTk5LCJleHAiOjE2NjY1OTYyMjl9.U_ZoOcD-xWn9R2yhbM8WRU7BwZJF-GfU-GH8WYLOJdw

###
GET http://localhost:5000/lecturer2/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbWVzMiIsInJvbGUiOiJbXCJsZWN0dXJlcjFcIl0iLCJpYXQiOjE2NjY2MjY1MjMsImV4cCI6MTY2NjYyNjU1M30.bYNN6iVuF1iK3v7HNIyH9q03sCDJWYJ5gtJ9Xl-D9gs


###
GET http://localhost:5000/admin/get/student/19363
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzIzMzI0OTAsImV4cCI6MTY3MjMzMzM5MH0.yL6kAMkx5BdwLSTrkHfrk_AC-42KxXf8V83D6Ih1X8k

###
GET http://localhost:5000/lecturer2/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJ1c2VybmFtZSI6ImphbWVzMTAzIiwicm9sZSI6IltcImFkbWluXCIsXCJsZWN0dXJlcjJcIl0iLCJpYXQiOjE2NjY2MDM2MTEsImV4cCI6MTY2NjYwMzY0MX0.0ujQRh5zLzW3bm3qAEZmHy5bBMStDsCwzMYIfHHju2k

###
POST http://localhost:5000/admin/get/lecturers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYwOTg0OTUsImV4cCI6MTY3NjA5OTM5NX0.i9owolputX_3YOH6aDzpTmzepKL4mlDt3J9XDv3OktI
Content-Type: application/json

{
    "id" : "",
    "username" : "",
    "title" : "",
    "email" : "",
    "supervisor" : "",
    "maximumTheses" : "2",
    "page" : "1"
}
###
POST http://localhost:5000/admin/update/signature
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzIwNjQ1MDgsImV4cCI6MTY3MjA2NTQwOH0.RPwHQDP0Z8YfmkaiFBQ0Hd8rrZgJYJMo_9RaQF2k-fg
Content-Type: application/json

{
    "signature" : "this is signature test"
}

###
GET http://localhost:5000/admin/get/signature
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzIwNjU3NjgsImV4cCI6MTY3MjA2NjY2OH0.fdhtVyRAPSp5Ecii30rNDkzFlrGYK1KkPwZECYv_fgE


###
POST http://localhost:5000/admin/add/lecturer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYwNDA1MTUsImV4cCI6MTY3NjA0MTQxNX0.D9zm7591dfGk7087FjwjtP_90ovFf2gyJ3E9fOAfoNg
Content-Type: application/json

{
    "id" : 21457,
    "username" : "haotran12",
    "email" : "haotran@gmail.com",
    "title" : "Dr. Hao Tran",
    "supervisor" : "lecturer1.1",
    "signature" : "signature",
    "maximumTheses" : 3,
    "bio" : "this is new bio"
}

###
PUT http://localhost:5000/admin/update/lecturer/21457
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYwNDEwMTQsImV4cCI6MTY3NjA0MTkxNH0.D2CDI9cfBIRmsxiaMdqCT3fByv6A8o-bv_oomYfT-Ck
Content-Type: application/json

{
    "username" : "linh",
    "fullname" : "linhkhanhtran_updated",
    "title" : "Dr. Linh",
    "email" : "linh1@gmail.com",
    "supervisor" : "lecturer1.1",
    "signature" : "signature",
    "maximumTheses" : "3",
    "bio" : "this is new update bio"
}

###
GET http://localhost:5000/admin/get/lecturer/21457
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYwNDExNjYsImV4cCI6MTY3NjA0MjA2Nn0.lwoCeB3ceIwF3zsLmCUPAvmJYnvjJZiLR5z1MJcQw3M

###
DELETE http://localhost:5000/admin/delete/lecturer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NzAzNDY4OSwiZXhwIjoxNjY3MDM0NzE5fQ.jWem9asn3mJG01BiqgTelT8GqfBT96MkfTPwFv364k0

###
GET http://localhost:5000/admin/get/testForm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzE4NjAxODMsImV4cCI6MTY3MTg2MTA4M30.mlPTH2X7uxhRQU80b94vtzxg0VyP9cOlm5j7xjRJquI
###
DELETE http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMyIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIyXCJdIiwiaWF0IjoxNjY2NTk2MTU5LCJleHAiOjE2NjY1OTYxODl9.hP6UbWaj7PPOMh9HIB4KlCUzCK1xR6qt-GhFp9CY_Ok