###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}

###
POST http://localhost:5000/admin/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk1MzA4OTEsImV4cCI6MTY2OTUzMTc5MX0.gFKsEr5jSyPtVNV1QomDVxpf471-H1ksaOM-YABi_Sk
Content-Type: application/json

{
    "id" : "",
    "thesisId" : "",
    "thesisTopic" : "",
    "lecturer1_id" : "",
    "lecturer2_id" : "",
    "lecturer1_title" : "",
    "lecturer2_title" : "",
    "slot" : "",
    "slotMaximum" : "",
    "page" : "1"
}

###
GET http://localhost:5000/admin/get/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDIxMjYsImV4cCI6MTY2ODQ0MzAyNn0.pCp3KO2-TXUYqo_cGboqIdXcbE_Qe6ml-XF3h8JUIxA


###
POST http://localhost:5000/admin/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDQ1MzUsImV4cCI6MTY2ODQ0NTQzNX0.FpnXk-2P1Cf8f0a3lyGiQs5CqYnN8YKa8zaWb5SfSeQ
Content-Type: application/json

{
    "thesisId" : 123412,
    "thesisTopic" : "Data For Everything",
    "thesisField" : "Data",
    "availableDay" : "2022-12-29",
    "defenseDay" : "2022-12-29",
    "slot" : "1",
    "slotMaximum" : "1"
}


###
PUT http://localhost:5000/admin/update/thesis/123412
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDQ4NTgsImV4cCI6MTY2ODQ0NTc1OH0.I4ilXE6iM5TcwugEMzAd3KIooNqpfWNoB_vT9joTI-4
Content-Type: application/json

{
    "thesisTopic" : "Data For Everything Update",
    "thesisField" : "Data Updated",
    "availableDay" : "2022-12-01",
    "defenseDay" : "2022-12-12",
    "slot" : "1",
    "slotMaximum" : "2"
}

###
DELETE http://localhost:5000/admin/delete/thesis/123412
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDU0OTYsImV4cCI6MTY2ODQ0NjM5Nn0.EGOoUkpirTJ_H_OwGc8CnvexIXdZ5DWK0vzeILP2W9k

###
POST http://localhost:5000/admin/assign/lecturerToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NDE4NjYsImV4cCI6MTY2ODg0Mjc2Nn0.0taga8bOpk28IolQNtNsmVGjCdLzLBhuZyiIAAyTbYY
Content-Type: application/json

{
    "lecturerId" : 21933,
    "thesisId" : 123122,
    "lecturer2" : 22323
}


###
POST http://localhost:5000/admin/assign/studentToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NDUxMTQsImV4cCI6MTY2ODg0NjAxNH0.khjMerdBqJaoQr3X-FKz_SLhr45bTfqX3Hecfm2Ofow
Content-Type: application/json

{
    "studentId" : 12365,
    "thesisId" : 123124
}