###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}

###
POST http://localhost:5000/admin/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYxMDAwMDYsImV4cCI6MTY3NjEwMDkwNn0.jcIwC0ptux_nLWRI1H9ViaUwEfrJ_ahh63xYIcAs9Sc
Content-Type: application/json

{
    "id" : "",
    "thesisId" : "",
    "thesisTopic" : "",
    "thesisField" : "",
    "availableDay" : "",
    "defenseDay" : "",
    "lecturer1_title" : "",
    "lecturer2_title" : "Pro",
    "slot" : "",
    "slotMaximum" : "",
    "page" : "1"
}

###
GET http://localhost:5000/admin/get/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYwOTk5MDAsImV4cCI6MTY3NjEwMDgwMH0.B_asB2neqdZVPndnPby8qiD4R3Gjm5lC5NEjRsOFIv8


###
POST http://localhost:5000/admin/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzYxMDA0NTksImV4cCI6MTY3NjEwMTM1OX0.1WTEi0rhV6-oUHPzDtuj8AL6dlOl6b_fZLMO-ligUx8
Content-Type: application/json

{
    "thesisTopic" : "Data For Everything",
    "thesisField" : "Data Testing",
    "lecturer1_id" : "23483",
    "lecturer2_id" : "22323",
    "slotMaximum" : 2
}


###
PUT http://localhost:5000/admin/update/thesis/123124
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzUzNDEzOTIsImV4cCI6MTY3NTM0MjI5Mn0.Ou8UidtKdSN3gNZAQUlg60GOIkIPgPAP1sHY6-jHlvA
Content-Type: application/json

{
    "thesisTopic" : "Data For Everything Update",
    "thesisField" : "Data Updated",
    "activateRegistration" : true,
    "activateDefense" : true,
    "numberOfHardCopies" : "2",
    "printRequirements" : "This is new requirements",
    "templateFiles" : "word",
    "submissionDeadline" : "2022-12-12"
}

###
DELETE http://localhost:5000/admin/delete/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDU0OTYsImV4cCI6MTY2ODQ0NjM5Nn0.EGOoUkpirTJ_H_OwGc8CnvexIXdZ5DWK0vzeILP2W9k

###
POST http://localhost:5000/admin/assign/lecturerToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzI2NDc4OTYsImV4cCI6MTY3MjY0ODc5Nn0.Zp26hpmERwHuN8tM5JSyVBhh5IOPYoi2MRLL9IZeuNE
Content-Type: application/json

{
    "lecturerId" : 23483,
    "thesisId" : 123122,
    "lecturer2" : 22323
}


###
POST http://localhost:5000/admin/assign/studentToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NzI2NDgzNDcsImV4cCI6MTY3MjY0OTI0N30.6R3ACUZPxtSixeEwhN0vMSZ8GbIzgZFbIGUPlX96N2o
Content-Type: application/json

{
    "studentId" : 12365,
    "thesisId" : 329852
}