###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}

###
POST http://localhost:5000/admin/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk4NzQxMTksImV4cCI6MTY2OTg3NTAxOX0.-kVUiUdyn3lhhFUWCqj95IHdrbOtGKRn0gxzHK6DQJw
Content-Type: application/json

{
    "id" : "",
    "thesisId" : "",
    "thesisTopic" : "",
    "thesisField" : "",
    "availableDay" : "",
    "defenseDay" : "",
    "slot" : "",
    "slotMaximum" : "1",
    "page" : "2"
}

###
GET http://localhost:5000/admin/get/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk4NzQwNTcsImV4cCI6MTY2OTg3NDk1N30.oByox5sDLSOQRNkSuW4D2Kf-0NgDqy-7XmlaItJzGWE


###
POST http://localhost:5000/admin/add/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk4ODIxMTgsImV4cCI6MTY2OTg4MzAxOH0.XGDQhQir9hqxESJ2hn5bEv95uDPN9lla-KExNyGDbUA
Content-Type: application/json

{
    "thesisId" : 123349,
    "thesisTopic" : "Data For Everything",
    "thesisField" : "Data Testing",
    "lecturer1_id" : "23483",
    "lecturer2_id" : "22323",
    "slotMaximum" : 2
}


###
PUT http://localhost:5000/admin/update/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk4ODQ1ODksImV4cCI6MTY2OTg4NTQ4OX0.cG68v4R8QY5VRPUOcj-WVyKvD_EMKAxgEgr8g8mn2A4
Content-Type: application/json

{
    "thesisTopic" : "Data For Everything Update",
    "thesisField" : "Data Updated",
    "activateRegistration" : true,
    "activateDefense" : false,
    "numberOfHardCopies" : "2",
    "printRequirements" : "This is new requirements",
    "templateFiles" : "word",
    "submissionDeadline" : "2022-12-12"
}

###
DELETE http://localhost:5000/admin/delete/thesis/123122
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0NDU0OTYsImV4cCI6MTY2ODQ0NjM5Nn0.EGOoUkpirTJ_H_OwGc8CnvexIXdZ5DWK0vzeILP2W9k

###
POST http://localhost:5000/admin/assign/lecturerToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NDE4NjYsImV4cCI6MTY2ODg0Mjc2Nn0.0taga8bOpk28IolQNtNsmVGjCdLzLBhuZyiIAAyTbYY
Content-Type: application/json

{
    "lecturerId" : 21933,
    "thesisId" : 123122,
    "lecturer2" : 22323
}


###
POST http://localhost:5000/admin/assign/studentToThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NDUxMTQsImV4cCI6MTY2ODg0NjAxNH0.khjMerdBqJaoQr3X-FKz_SLhr45bTfqX3Hecfm2Ofow
Content-Type: application/json

{
    "studentId" : 12365,
    "thesisId" : 123124
}