POST http://localhost:4000/signup
Content-Type: application/json

{
    "id" : "30000",
    "username" : "lukas",
    "password" : "30000",
    "role" : ["admin"]
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}
###
GET http://localhost:5000/getNotifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NTM3NjUsImV4cCI6MTY2ODg1NDY2NX0.VQWbboVYlebRCShIWrluYG_IV1XS4ajxRZnA-4tuSv0

###
GET http://localhost:4000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NjgwMDI5MCwiZXhwIjoxNjY2ODAwMzIwfQ.gZgsEh7TR89gz8yuA0iwrkx9Pw7xzbu4pOBNx6tJuyk
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTE5MCwiZXhwIjoxNjY2NDM4NzkwfQ.hKxDcBkq15hNjD9W8TPp1uErxPpG1TTGGIW0-DQjYVU"
}

###
GET http://localhost:5000/admin/get/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxNjYzMjcsImV4cCI6MTY2ODE2NjM1N30.gPxyJo4AmL92o-Slzcqfpa4k-lXA092S99FzaNeaAH0

###
GET http://localhost:5000/admin/get1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqYW1lczIiLCJyb2xlIjoibGVjdHVyZXIxIiwiaWF0IjoxNjY2NDE2NzkxLCJleHAiOjE2NjY0MTY4MjF9.TxOqq6TGCqAkuNVt3ARtDaiARcHPKfib1sumYLa8zq4

###
GET http://localhost:5000/admin/get2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQxNzYwMCwiZXhwIjoxNjY2NDE3NjMwfQ.bpYOUSeeK1f-D9shUCENja1Tq7VGyyGj4Qajt_lRRXU


###
GET http://localhost:5000/lecturer1/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqYW1lczEwMSIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIxXCJdIiwiaWF0IjoxNjY2NTk2MTk5LCJleHAiOjE2NjY1OTYyMjl9.U_ZoOcD-xWn9R2yhbM8WRU7BwZJF-GfU-GH8WYLOJdw

###
GET http://localhost:5000/lecturer2/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbWVzMiIsInJvbGUiOiJbXCJsZWN0dXJlcjFcIl0iLCJpYXQiOjE2NjY2MjY1MjMsImV4cCI6MTY2NjYyNjU1M30.bYNN6iVuF1iK3v7HNIyH9q03sCDJWYJ5gtJ9Xl-D9gs


###
GET http://localhost:5000/student/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTczNSwiZXhwIjoxNjY2NDM1NzY1fQ.1uXkapiACWg1K0YnoO5bgWHp9WCjGMKWF1OjFLZktIY

###
GET http://localhost:5000/lecturer2/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJ1c2VybmFtZSI6ImphbWVzMTAzIiwicm9sZSI6IltcImFkbWluXCIsXCJsZWN0dXJlcjJcIl0iLCJpYXQiOjE2NjY2MDM2MTEsImV4cCI6MTY2NjYwMzY0MX0.0ujQRh5zLzW3bm3qAEZmHy5bBMStDsCwzMYIfHHju2k

###
POST http://localhost:5000/admin/get/lecturers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg0MjAzODAsImV4cCI6MTY2ODQyMTI4MH0.uXzlKG13OBKAMEpQ9lpUoYi18b6z2KPvKb0XQJAJmNc
Content-Type: application/json

{
    "id" : "21029",
    "username" : "",
    "fullname" : "",
    "title" : "",
    "email" : "",
    "supervisor" : "",
    "page" : "1"
}


###
POST http://localhost:5000/admin/add/lecturer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxNjgxOTIsImV4cCI6MTY2ODE2ODIyMn0.VvXtu86FnLgvt1VuHITmA2KmXyxKtZ11GpaqWOdYUYw
Content-Type: application/json

{
    "id" : 12312,
    "username" : "123541",
    "fullname" : "haotran",
    "email" : "haotran@gmail.com",
    "title" : "Dr. Hao Tran",
    "supervisor" : "lecturer1",
    "signature" : "signature"
}

###
PUT http://localhost:5000/admin/update/lecturer/21029
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxODY1ODYsImV4cCI6MTY2ODE4NjYxNn0.wuNGGSelFkslUQ7Admu5qTTmLlx_kjBmGDC3a9wCeaA
Content-Type: application/json

{
    "username" : "linh",
    "fullname" : "linhkhanhtran_updated",
    "title" : "Dr. Linh",
    "email" : "linh1@gmail.com",
    "supervisor" : "lecturer2",
    "signature" : "signature"
}

###
GET http://localhost:5000/admin/get/lecturer/21029
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2NjgxNjY0MjYsImV4cCI6MTY2ODE2NjQ1Nn0.2wmikTlGEpR8mM8FwqfJPij0C6D0sBc26m4S4Skt044

###
DELETE http://localhost:5000/admin/delete/lecturer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NzAzNDY4OSwiZXhwIjoxNjY3MDM0NzE5fQ.jWem9asn3mJG01BiqgTelT8GqfBT96MkfTPwFv364k0

###
GET http://localhost:5000/admin/delete/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NzAzNDY0NCwiZXhwIjoxNjY3MDM0Njc0fQ.Lz-wWgeZ0tGeiIoVKA3xgEKaHmA0roXEdskqRpDhulg
###
DELETE http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMyIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIyXCJdIiwiaWF0IjoxNjY2NTk2MTU5LCJleHAiOjE2NjY1OTYxODl9.hP6UbWaj7PPOMh9HIB4KlCUzCK1xR6qt-GhFp9CY_Ok