POST http://localhost:4000/signup
Content-Type: application/json

{
    "username" : "james103",
    "password" : "james103",
    "role" : ["admin", "lecturer2"]
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "james103",
    "password" : "james103"
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTE5MCwiZXhwIjoxNjY2NDM4NzkwfQ.hKxDcBkq15hNjD9W8TPp1uErxPpG1TTGGIW0-DQjYVU"
}

###
GET http://localhost:5000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMSIsInJvbGUiOiJbXCJzdHVkZW50XCIsXCJhZG1pblwiXSIsImlhdCI6MTY2NjQxNTQ2MywiZXhwIjoxNjY2NDE1NDkzfQ.V3hajOYU5YkAS68VmQ5RUSWrzOSw4BqLj74NKvF9b1g

###
GET http://localhost:5000/admin/get1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqYW1lczIiLCJyb2xlIjoibGVjdHVyZXIxIiwiaWF0IjoxNjY2NDE2NzkxLCJleHAiOjE2NjY0MTY4MjF9.TxOqq6TGCqAkuNVt3ARtDaiARcHPKfib1sumYLa8zq4

###
GET http://localhost:5000/admin/get2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQxNzYwMCwiZXhwIjoxNjY2NDE3NjMwfQ.bpYOUSeeK1f-D9shUCENja1Tq7VGyyGj4Qajt_lRRXU


###
GET http://localhost:5000/lecturer1/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJqYW1lczEwMiIsInJvbGUiOiJbXCJsZWN0dXJlcjJcIixcImxlY3R1cmVyMVwiXSIsImlhdCI6MTY2NjQxNzk0OCwiZXhwIjoxNjY2NDE3OTc4fQ.s66HxVqKlAz9nhOfkddZIMvkNo3TcfO7rdntBzWQNII

###
GET http://localhost:5000/lecturer2/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJqYW1lczMiLCJyb2xlIjoibGVjdHVyZXIyIiwiaWF0IjoxNjY2NDE4NTY1LCJleHAiOjE2NjY0MTg1OTV9.ahhB9fmNgqelMzFkzTPaeWTsxFPxNf5KkzTDl0OrMwQ


###
GET http://localhost:5000/student/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTczNSwiZXhwIjoxNjY2NDM1NzY1fQ.1uXkapiACWg1K0YnoO5bgWHp9WCjGMKWF1OjFLZktIY

###
GET http://localhost:5000/lecturer2/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMyIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIyXCJdIiwiaWF0IjoxNjY2NDM2ODQ1LCJleHAiOjE2NjY0MzY4NzV9.uEvCoLXvjtCxwI7J7LcTe4--7U7J9v-m4Lbx35UdfkA



###
DELETE http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTY0NywiZXhwIjoxNjY2NDM1Njc3fQ.7va1jmxsYrcbPiBmj-7WZAyQZ6NBDthxbTkbAS_bZQ8