POST http://localhost:4000/signup
Content-Type: application/json

{
    "id" : "30000",
    "username" : "lukas",
    "password" : "30000",
    "role" : ["admin"]
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "lukas",
    "password" : "30000"
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTE5MCwiZXhwIjoxNjY2NDM4NzkwfQ.hKxDcBkq15hNjD9W8TPp1uErxPpG1TTGGIW0-DQjYVU"
}

###
GET http://localhost:5000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMSIsInJvbGUiOiJbXCJzdHVkZW50XCIsXCJhZG1pblwiXSIsImlhdCI6MTY2NjQxNTQ2MywiZXhwIjoxNjY2NDE1NDkzfQ.V3hajOYU5YkAS68VmQ5RUSWrzOSw4BqLj74NKvF9b1g

###
GET http://localhost:5000/admin/get1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqYW1lczIiLCJyb2xlIjoibGVjdHVyZXIxIiwiaWF0IjoxNjY2NDE2NzkxLCJleHAiOjE2NjY0MTY4MjF9.TxOqq6TGCqAkuNVt3ARtDaiARcHPKfib1sumYLa8zq4

###
GET http://localhost:5000/admin/get2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQxNzYwMCwiZXhwIjoxNjY2NDE3NjMwfQ.bpYOUSeeK1f-D9shUCENja1Tq7VGyyGj4Qajt_lRRXU


###
GET http://localhost:5000/lecturer1/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqYW1lczEwMSIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIxXCJdIiwiaWF0IjoxNjY2NTk2MTk5LCJleHAiOjE2NjY1OTYyMjl9.U_ZoOcD-xWn9R2yhbM8WRU7BwZJF-GfU-GH8WYLOJdw

###
GET http://localhost:5000/lecturer2/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbWVzMiIsInJvbGUiOiJbXCJsZWN0dXJlcjFcIl0iLCJpYXQiOjE2NjY2MjY1MjMsImV4cCI6MTY2NjYyNjU1M30.bYNN6iVuF1iK3v7HNIyH9q03sCDJWYJ5gtJ9Xl-D9gs


###
GET http://localhost:5000/student/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiamFtZXMxMDMiLCJyb2xlIjoiW1wiYWRtaW5cIixcImxlY3R1cmVyMlwiXSIsImlhdCI6MTY2NjQzNTczNSwiZXhwIjoxNjY2NDM1NzY1fQ.1uXkapiACWg1K0YnoO5bgWHp9WCjGMKWF1OjFLZktIY

###
GET http://localhost:5000/lecturer2/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJ1c2VybmFtZSI6ImphbWVzMTAzIiwicm9sZSI6IltcImFkbWluXCIsXCJsZWN0dXJlcjJcIl0iLCJpYXQiOjE2NjY2MDM2MTEsImV4cCI6MTY2NjYwMzY0MX0.0ujQRh5zLzW3bm3qAEZmHy5bBMStDsCwzMYIfHHju2k

###
POST http://localhost:5000/admin/get/lecturers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2NjcwOTQyMywiZXhwIjoxNjY2NzA5NDUzfQ.NR3rTEcbXE8N4528S2rFRnaMdTVdrgkFuTEPXa1A8SM
Content-Type: application/json

{
    "id" : "",
    "username" : "",
    "fullname" : "",
    "email" : "",
    "supervisor" : "",
    "page" : "2"
}


###
POST http://localhost:5000/admin/add/lecturer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2Njc2NzI2NiwiZXhwIjoxNjY2NzY3Mjk2fQ.kvFuoQZ8K4h06U3FOMdNXqnOGcSIrarAZeR26OxLXBo
Content-Type: application/json

{
    "id" : 22311,
    "username" : "haotran",
    "fullname" : "haotran",
    "email" : "haotran@gmail.com",
    "supervisor" : "1"
}

###
POST http://localhost:5000/admin/update/lecturer/21933
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2Njc3MDA0MywiZXhwIjoxNjY2NzcwMDczfQ.9c_UJ-KKfp8d7oZHbypmziPIfJNraigoXwJVhtWO684
Content-Type: application/json

{
    "username" : "linhkhanh_updated",
    "fullname" : "linhkhanhtran_updated",
    "email" : "linh1@gmail.com",
    "supervisor" : "2"
}

###
POST http://localhost:5000/admin/get/lecturer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDAwIiwidXNlcm5hbWUiOiJsdWthcyIsInJvbGUiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY2Njc2OTU0NCwiZXhwIjoxNjY2NzY5NTc0fQ.O7uijuNksVhtNiCWBRe2RQpTuT245O6oNC8xHp4CLcA

###
DELETE http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqYW1lczEwMyIsInJvbGUiOiJbXCJhZG1pblwiLFwibGVjdHVyZXIyXCJdIiwiaWF0IjoxNjY2NTk2MTU5LCJleHAiOjE2NjY1OTYxODl9.hP6UbWaj7PPOMh9HIB4KlCUzCK1xR6qt-GhFp9CY_Ok