
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "dnoakes1",
    "password" : "12486"
}

###
GET http://localhost:5000/student/get/12486
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njg4NTM3NjUsImV4cCI6MTY2ODg1NDY2NX0.VQWbboVYlebRCShIWrluYG_IV1XS4ajxRZnA-4tuSv0



###

POST http://localhost:5000/student/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2ODkzMjUyNywiZXhwIjoxNjY4OTMzNDI3fQ.Ro8uls0wnffxT8L9hTFhIqKBa76sWs8Cx1Xo96RndoA
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateOfBirth" : "2000-12-23",
    "placeOfBirth" : "HCM city",
    "signature" : "",
    "titleBachelorThesis" : "Data Mining",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_signature" : "",
    "supervisor1_date" : "2022-12-12",
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_signature" : "",
    "supervisor2_date" : "2022-12-12",
    "issued" : "2023-1-12",
    "deadlineCopy" : 2,
    "extensionGranted" : "2022-12-29",
    "chairmanOfExamination" : "VGU",
    "date_of_issue" : "2000-12-23"
}

###

POST http://localhost:5000/student/registrationOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2ODk1MjM3NSwiZXhwIjoxNjY4OTUzMjc1fQ.r_Y1Ux7itTH_w-xCJzA4hMz5Wp4gJDGgEmy3YHqlNvc
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor2_title" : "Master Huynh Nguyen", 
    "spectatorsPresent" : 1,
    "weekDate" : "3", 
    "proposedDate" : "2022-12-29", 
    "proposedTime" : "07:00:00", 
    "room" : "A2392.3", 
    "concernedAgreed" : 1, 
    "dateReceive" : "2023-03-29", 
    "dateSubmission" : "2023-03-29"
}

###

POST http://localhost:5000/student/assessmentBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2OTAyNDExNSwiZXhwIjoxNjY5MDI1MDE1fQ.ELhFB-39ejuHD87cELFqFsc6QdnaITwzzDlQrxKEgkc
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_grade" : 1.5,
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_grade" : 1.2,
    "assessmentThesis" : "This is assessment Thesis",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###

POST http://localhost:5000/student/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2OTAyOTY4OSwiZXhwIjoxNjY5MDMwNTg5fQ.Y1rKXD_EDATZzIsOjlrhav7Sw_ABjv98B2F2BILIF4c
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen", 
    "supervisor2_grade" : 1.3,
    "record" : "This is record",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
POST http://localhost:5000/student/get/lecturers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTY0ODcyOCwiZXhwIjoxNjcxNjQ5NjI4fQ.ltWhrpIB1deeA8hmd22U4x1E1FXVHlF0RyXhNfC7Rqw
Content-Type: application/json

{
    "lecturerId" : "",
    "lecturerTitle" : "",
    "lecturerFullName" : "",
    "email" : "",
    "supervisor" : "",
    "isAvailable" : true,
    "page" : 2
}

###
GET http://localhost:5000/student/get/lecturer/21029
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTY1MTA1MCwiZXhwIjoxNjcxNjUxOTUwfQ.iWTIOloO9iACzHchZZeqlg_1MBAG5kpLyt85GZioa7Y

###
PUT http://localhost:5000/admin/update/student/13961/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAwMDAsInVzZXJuYW1lIjoibHVrYXMiLCJyb2xlIjoiW1wiYWRtaW5cIl0iLCJpYXQiOjE2Njk5NzMzMDYsImV4cCI6MTY2OTk3NDIwNn0.w6-usDeiWXu27l44Fp1Yad4Go1D626RpqMHvpkbO0Fc
Content-Type: application/json

{
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateOfBirth" : "2000-12-23",
    "placeOfBirth" : "HCM city",
    "signature" : "",
    "titleBachelorThesis" : "Data Mining",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_signature" : "",
    "supervisor1_date" : "2022-12-12",
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_signature" : "",
    "supervisor2_date" : "2022-12-12",
    "issued" : "2023-1-12",
    "deadlineCopy" : 2,
    "extensionGranted" : "2022-12-29",
    "chairmanOfExamination" : "VGU",
    "dateOfIssue" : "2022-12-23"
}

###
GET http://localhost:5000/student/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTAyNjI2NCwiZXhwIjoxNjcxMDI3MTY0fQ.fd2LX1ccsHOhogkhAB-yXqkLJzw2cfIsLemW7XTkrSw

###
GET http://localhost:5000/student/get/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MDUwMzczNywiZXhwIjoxNjcwNTA0NjM3fQ.u53BqvJfjeJPoO1a8jczxqB4J4aOA4TVvrKnl0BTOh4

###
POST http://localhost:5000/student/add/confirmSup1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTM0NDQsInVzZXJuYW1lIjoiYWJlenphbnQ2Iiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2NzA1MDc4NjYsImV4cCI6MTY3MDUwODc2Nn0.XsU5TQmsztBuk3XFiyEq57WXW-HD6ixgZv92Ejl2sKk
Content-Type: application/json

{
    "thesisId" : "123122"
}

###
PUT http://localhost:5000/student/update/confirmSup2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTcxODI2NSwiZXhwIjoxNjcxNzE5MTY1fQ.bZDb-P4iHysRvfGe8Lh0i8ceOhFaLRO_hd9JqTvtRdc
Content-Type: application/json

{
    "lecturer2_id" : "25489"
}

###
GET http://localhost:5000/student/get/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTYzNzk3NywiZXhwIjoxNjcxNjM4ODc3fQ.-m0bSrVck2lWo0xO9zh0OJSYIzXoGJ2IDBzsAW7I5l0
