
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "arickell3",
    "password" : "19363"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "datnguyen",
    "password" : "12345"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "abezzant6",
    "password" : "13444"
}
###
GET http://localhost:5000/student/get/12486
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3NjI5MDk3MSwiZXhwIjoxNjc2MjkxODcxfQ.cdgvUDF1lSu6OP_CRkrFrNNF7UEbSR_mr4SRuhtU5x0



###
POST http://localhost:5000/student/add/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MzUwOTc5MiwiZXhwIjoxNjczNTEwNjkyfQ.mKtqJ_-QyhbCqluCspGtNZG4ms2_Fh0LN1A4L4KnmoY
Content-Type: application/json

{
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateOfBirth" : "2000-12-23",
    "placeOfBirth" : "HCM city",
    "signature" : "",
    "student_date" : "2022-12-2",
    "titleBachelorThesis" : "Data Mining",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_signature" : "",
    "supervisor1_date" : "2022-12-12",
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_signature" : "",
    "supervisor2_date" : "2022-12-12",
    "issued" : "2023-1-12",
    "deadlineCopy" : 2,
    "extensionGranted" : "2022-12-29",
    "chairmanOfExamination" : "VGU",
    "date_of_issue" : "2000-12-23"
}

###

POST http://localhost:5000/student/registrationOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2ODk1MjM3NSwiZXhwIjoxNjY4OTUzMjc1fQ.r_Y1Ux7itTH_w-xCJzA4hMz5Wp4gJDGgEmy3YHqlNvc
Content-Type: application/json

{
    "studentId" : 11475,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor2_title" : "Master Huynh Nguyen", 
    "spectatorsPresent" : 1,
    "weekDate" : "3", 
    "proposedDate" : "2022-12-29", 
    "proposedTime" : "07:00:00", 
    "room" : "A2392.3", 
    "concernedAgreed" : 1, 
    "dateReceive" : "2023-03-29", 
    "dateSubmission" : "2023-03-29"
}

###

POST http://localhost:5000/student/assessmentBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY2OTAyNDExNSwiZXhwIjoxNjY5MDI1MDE1fQ.ELhFB-39ejuHD87cELFqFsc6QdnaITwzzDlQrxKEgkc
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_grade" : 1.5,
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_grade" : 1.2,
    "assessmentThesis" : "This is assessment Thesis",
    "assessmentDate" : "2022-12-29",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###

PUT http://localhost:5000/student/assessmentOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3NTc5NTg4MywiZXhwIjoxNjc1Nzk2NzgzfQ.4Q2jE6384iYlFnHkcKw9qRl-X_1diaOF3xNKWskevqM
Content-Type: application/json

{
    "studentId" : 12486,
    "matriculationNumber" : 1238432,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateDefense" : "2023-03-19",
    "placeDefense" : "HCM city",
    "startDate" : "2022-12-29",
    "finishDate" : "2023-03-19",
    "stateOfHealth" : 1,
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor1_grade" : 1.1,
    "supervisor2_title" : "Master Huynh Nguyen", 
    "supervisor2_grade" : 1.3,
    "record" : "This is record",
    "assessmentDate" : "2023-03-19",
    "supervisor1_signature" : "",
    "supervisor2_signature" : ""
}

###
POST http://localhost:5000/student/get/lecturers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3NjI4OTM2MSwiZXhwIjoxNjc2MjkwMjYxfQ.T-qs-7edv0C3lHp-qZoXb_xwvYimIB2q5IUzSKHI4Wg
Content-Type: application/json

{
    "lecturerId" : "",
    "lecturerTitle" : "",
    "email" : "",
    "supervisor" : "",
    "isAvailable" : true,
    "page" : 1
}

###
GET http://localhost:5000/student/get/lecturer/23483
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3NjMwNDUzNCwiZXhwIjoxNjc2MzA1NDM0fQ.6OO2eQiGCFA8bqi_UZRLyZVk5Ow_zMHnG0WLvjT7GY4


###
GET http://localhost:5000/student/get/theses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MTAyNjI2NCwiZXhwIjoxNjcxMDI3MTY0fQ.fd2LX1ccsHOhogkhAB-yXqkLJzw2cfIsLemW7XTkrSw

###
GET http://localhost:5000/student/get/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3MDUwMzczNywiZXhwIjoxNjcwNTA0NjM3fQ.u53BqvJfjeJPoO1a8jczxqB4J4aOA4TVvrKnl0BTOh4

###
POST http://localhost:5000/student/add/confirmSup1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTM0NDQsInVzZXJuYW1lIjoiYWJlenphbnQ2Iiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2Nzg3ODE0NjgsImV4cCI6MTY3ODc4MjM2OH0.JwDul5mb_-NweGiGD-zNrHfPESZySyhCHOrjcViQNjM
Content-Type: application/json

{
    "thesisId" : "123554"
}

###
PUT http://localhost:5000/student/update/confirmSup2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzNDUsInVzZXJuYW1lIjoiZGF0bmd1eWVuIiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2NzkwMzg1NDIsImV4cCI6MTY3OTAzOTQ0Mn0.6ZrKBY3htFqSCjLcge6vsKli7ZfVsyiVcQhW5ld6ycQ
Content-Type: application/json

{
    "lecturer2_id" : "20489"
}

###
PUT http://localhost:5000/student/update/registrationBachelorThesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTkzNjMsInVzZXJuYW1lIjoiYXJpY2tlbGwzIiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2Nzk5MjIwNjAsImV4cCI6MTY3OTkyMjk2MH0.NXl17v64-rBvxWi36B3gFaNPU5bnCECwoNZu9xWg0cQ
Content-Type: application/json

{
    "matriculationNumber" : 1232312,
    "surName" : "phannguyen",
    "foreName" : "long",
    "dateOfBirth" : "2000-12-23",
    "placeOfBirth" : "HCM city",
    "signature" : "",
    "student_date" : "2022-12-2",
    "titleBachelorThesis" : "Data Mining",
    "thesisType" : "1",
    "furtherParticipants" : "",
    "supervisor1_title" : "Prof. Huynh Trung Hieu",
    "supervisor1_signature" : "",
    "supervisor1_date" : "2022-12-12",
    "supervisor2_title" : "Master Huynh Nguyen",
    "supervisor2_signature" : "",
    "supervisor2_date" : "2022-12-12",
    "issued" : "2023-1-12",
    "deadlineCopy" : 2,
    "extensionGranted" : "2022-12-29",
    "chairmanOfExamination" : "VGU",
    "dateOfIssue" : "2000-12-23"
}

###

PUT http://localhost:5000/student/update/registrationOralDefense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTkzNjMsInVzZXJuYW1lIjoiYXJpY2tlbGwzIiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2Nzk5MjIwNjAsImV4cCI6MTY3OTkyMjk2MH0.NXl17v64-rBvxWi36B3gFaNPU5bnCECwoNZu9xWg0cQ
Content-Type: application/json

{
    "matriculationNumber" : 1232312,
    "surName" : "phannguyen",
    "foreName" : "long",
    "supervisor1_title" : "Prof Huynh Trung Hieu",
    "supervisor2_title" : "Master Huynh Nguyen", 
    "spectatorsPresent" : 1,
    "weekDate" : "3", 
    "proposedDate" : "2023-03-29", 
    "proposedTime" : "07:00:00", 
    "room" : "A2392.3", 
    "concernedAgreed" : 1, 
    "dateReceive" : "2023-03-29", 
    "dateSubmission" : "2023-03-29"
}


###
GET http://localhost:5000/student/get/thesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzNDUsInVzZXJuYW1lIjoiZGF0bmd1eWVuIiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2Nzg5NTAyOTUsImV4cCI6MTY3ODk1MTE5NX0.W25mNvhClOIFrvQN7JGES07GFEYmBpGn6v0pOs6Qfrk

###
GET http://localhost:5000/student/update/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI0ODYsInVzZXJuYW1lIjoiZG5vYWtlczEiLCJyb2xlIjoiW1wic3R1ZGVudFwiXSIsImlhdCI6MTY3NTYyMTQxNCwiZXhwIjoxNjc1NjIyMzE0fQ.JGAGGTLqlc0KWPfoTanEPGCQur-t2Kz6ITxfinRkKfI
Content-Type: application/json

{
    "signature" : "sign student"
}
###
GET http://localhost:5000/student/get/testForm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE0NzUsInVzZXJuYW1lIjoiZHBhbXBsaW41Iiwicm9sZSI6IltcInN0dWRlbnRcIl0iLCJpYXQiOjE2Nzg5ODgwMjYsImV4cCI6MTY3ODk4ODkyNn0.fEjzi0OvU02nT-LVc8LhVLvAPlESZGjzpieIjM8gIGE